version: "3.8"

services:
  db:
    image: postgres:16
    container_name: chat_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: chat_db
      POSTGRES_MAX_CONNECTIONS: 500
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  atlas-db:
    image: postgres:16
    container_name: atlas_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: atlas_db
    volumes:
      - atlas-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: chat_redis
    ports:
      - "6389:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  db-data:
  atlas-db-data:
